### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by baqwas** [arduino-libraries/USBHostGiga#1]
Is it possible to get a paragraph or two on the installation of this library on the following platforms?

- Windows 11
- Max OS X
- Linux (at least the more popular ones)

I understand the alpha designation but perhaps in the interest of the wider community there should some nominal steps provided to users who are not full-time developers. Thanks.

Regards.

**Comment by per1234** [comment]
I have provided instructions on @baqwas's post on Arduino Forum:

https://forum.arduino.cc/t/makefile-for-usbhostgiga/1109099

**Comment by baqwas** [comment]
My apologies, @per1234. I seem to have _forgotten_ how to use libraries in Arduino. Dementia must be setting in or else very slow thinking on my part. Thanks for setting me straight.

Regards.
