### ISSUE TITLE
Remapping keys

### ISSUE THREAD

**Issue by ghost** [arduino-libraries/USBHostGiga#3]
Hi
I need to remap keys on my keyboard but I can't upgrade my keyboard's firmware (ex. when I press A, the arduino outputs 'B'). Is there a way to accomplish to this? Thank you!

**Comment by per1234** [comment]
Hi @I7hub. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
